name = "DFUtils"
uuid = "f5eb988d-82e1-498f-b360-bbd92a0181ed"
authors = ["Daniel Winkler <danielw2904@disroot.org> and contributors"]
version = "0.2.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
BenchmarkTools = "0.5, 0.6, 0.7"
DataFrames = "0.21, 0.22"
Missings = "0.4"
Parsers = "1.0"
Transducers = "0.4"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
